version: '2'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./configs/httpd/devops.site.conf:/etc/apache2/sites-available/000-default.conf"
      - "./configs/app/.env:/var/www/html/myapp/.env"
      - "./configs/app/config_app.sh:/tmp/config_app.sh"
      - "/var/www/myapp:/var/www/html/myapp"
    ports:
      - "8081:80" 
    command: echo "cd /var/www/html/myapp "
    command: cd /var/www/html/myapp ; pwd
    command: pwd
    command: echo "php -dmemory_limit=750M composer.phar update --no-scripts --prefer-dist"
    command: php -dmemory_limit=750M composer.phar update --no-scripts --prefer-dist
    depends_on:
      - db_server
  db_server:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #creará una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
    ports:
      - "4400:3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"
    command: echo "mysql -uroot -proot devops_app < /tmp/script.sql"
    command: mysql -uroot -proot devops_app < /tmp/script.sql

