version: '2'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./configs/httpd/devops.site.conf:/etc/apache2/sites-available/000-default.conf
      - ./.env:/var/www/html/myapp/.env
      - ./configs/app/config_app.sh:/tmp/config_app.sh
      - /var/www/myapp:/var/www/html/myapp
    expose:
      - 8081
    ports:
      - 8081:80 
      - 8142:8140
    depends_on:
      - mysql
    env_file:
      - ./configs/app/.env
  
  mysql:
    image: mysql:5.7 
    container_name: dbmysql
    environment:
      - MYSQL_DATABASE=devops_app       #creará una base de datos con ese nombre
      - MYSQL_ROOT_USER=root            #usuario de administrador del servidor MySQL
      - MYSQL_ROOT_PASSWORD=root        #clave de administrador del servidor MySQL
       #You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
    expose:
      - 3306
    ports:
      - 3306:3306
      - 8141:8140
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - ./configs/mysql/script.sql:/tmp/script.sql 
    command: 
      - bash 
      - -c 
      - |    
             apt-get update && apt-get install systemd -y
             ln -sf /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime
             apt-get install software-properties-common -y
             add-apt-repository 'deb http://archive.ubuntu.com/ubuntu $$(lsb_release -sc) universe' 
             apt install -y puppet 
             apt-get -y install ntp
             service ntp start 
             rm -rf /var/lib/puppet/ssl 
             service puppet start && puppet node clean utn-devops.localhost && puppet agent --certname utn-devops.localhost --enable