version: '2'
services:
  php:
    container_name: apache2_php
    build: .
    volumes:
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./configs/httpd/devops.site.conf:/etc/apache2/sites-available/000-default.conf"
      - "./configs/app/.env:/var/www/html/myapp/.env"
      - "./configs/app/config_app.sh:/tmp/config_app.sh"
      - "/var/www/myapp:/var/www/html/myapp"
    expose:
      - "8081"
    ports:
      - "8081:80" 
    links:
      - mysql:mysql
  
  mysql:
    image: mysql:5.7
    container_name: db_mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=devops_app #creará una base de datos con ese nombre
      - MYSQL_ROOT_USER=root #usuario de administrador del servidor MySQL
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"